<a href="https://colab.research.google.com/github/naveenpittala/Assignmnet1/blob/master/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# A marathon problem

In [0]:
import numpy as np #generating random 
a=np.random.randint(10, size=(10, 20))
print(a)

[[1 0 9 6 2 2 0 3 8 5 9 7 8 7 4 7 2 5 6 7]
 [4 8 6 1 6 6 2 9 6 0 3 4 4 6 7 5 2 1 5 7]
 [4 3 9 1 8 7 4 5 4 9 0 2 1 6 4 0 5 0 9 7]
 [3 8 6 3 3 8 7 4 1 8 9 2 9 1 7 9 5 5 1 7]
 [0 7 2 0 0 7 6 7 6 4 8 0 6 6 1 9 1 8 1 1]
 [8 1 1 1 3 3 6 9 6 9 1 5 8 9 6 0 8 9 8 5]
 [9 5 6 8 8 0 2 2 0 8 3 4 9 5 0 9 5 2 6 3]
 [6 6 7 0 1 0 9 7 2 7 8 7 5 5 7 3 6 8 4 1]
 [1 0 8 1 4 2 5 7 2 8 4 7 2 5 2 1 5 0 2 2]
 [4 3 5 1 7 0 1 5 9 4 7 3 4 5 2 3 5 5 4 3]]


In [0]:
b=np.random.randint(10, size=(1, 20)) #length of each track
print(b)

[[6 9 3 4 3 3 2 0 6 1 7 9 1 7 0 5 4 7 8 1]]


In [0]:
d=a*b
print(d)

[[ 6  0 27 24  6  6  0  0 48  5 63 63  8 49  0 35  8 35 48  7]
 [24 72 18  4 18 18  4  0 36  0 21 36  4 42  0 25  8  7 40  7]
 [24 27 27  4 24 21  8  0 24  9  0 18  1 42  0  0 20  0 72  7]
 [18 72 18 12  9 24 14  0  6  8 63 18  9  7  0 45 20 35  8  7]
 [ 0 63  6  0  0 21 12  0 36  4 56  0  6 42  0 45  4 56  8  1]
 [48  9  3  4  9  9 12  0 36  9  7 45  8 63  0  0 32 63 64  5]
 [54 45 18 32 24  0  4  0  0  8 21 36  9 35  0 45 20 14 48  3]
 [36 54 21  0  3  0 18  0 12  7 56 63  5 35  0 15 24 56 32  1]
 [ 6  0 24  4 12  6 10  0 12  8 28 63  2 35  0  5 20  0 16  2]
 [24 27 15  4 21  0  2  0 54  4 49 27  4 35  0 15 20 35 32  3]]


In [0]:
# Who ran for maximum total distance?
d.sum(axis=1).argmax()

0

In [0]:
# Who ran for minimum total distance?
d.sum(axis=1).argmin()

8

In [0]:
# Who ran for maximum distance in each track
d.argmax(axis=0)

array([6, 1, 0, 6, 2, 3, 7, 0, 9, 2, 0, 0, 3, 5, 0, 3, 5, 5, 2, 0])

In [0]:
# Who ran for minimum distance in each track
d.argmin(axis=1)

array([1, 7, 7, 7, 0, 7, 5, 3, 1, 5])

In [0]:
 # How much did B run in total?
 d[1].sum()

384

In [0]:
#  How much did C run in total on track 0, 1 and 2?
d[2,[0,1,2]].sum()

78

In [0]:
# How much did D run in total on track 0, 2 and 3?
d[3,[0,2,3]].sum()

48

In [0]:
# How much did C, D and E run in total on track 0, 2 and 3?
d[[2],[0,2,3]].sum() + d[[3],[0,2,3]].sum() + d[[4],[0,2,3]].sum()

In [0]:
## How many person beat A on track 1 ?
a[,[1]]>0


In [0]:
## How many person beat A in terms of total distance covered on track 0, 1 and 3?
d[0:,[0,1,3]].sum()

697

In [0]:
# How much more did A run in comparison to E?
d[0].sum()-d[4].sum()

78

In [0]:
 # What is the average distance covered by players on track 0?
 d[:,0].mean(axis=0)

24.0

In [0]:
# What is the average distance covered by A on all tracks combined?
 d[0,:].mean() #oth row and all the columns

21.9

In [0]:
#  What is the average distance ran by each player in total on all tracks combined?
d.mean(axis=1)

array([21.9 , 19.2 , 16.4 , 19.65, 18.  , 21.3 , 20.8 , 21.9 , 12.65,
       18.55])

In [0]:
# Which track was used the most?
d.sum(axis=0).argmax()

13

In [0]:
# which track was used the least? 
d.sum(axis=0).argmin()

7

In [0]:
# Which is the longest track?
b.argmax()

1

In [0]:
# How many laps was covered on track 3 in average by all players?
a[:,3].mean()

2.2

In [0]:
# Marathon problem ends here

In [0]:
# More on numpy

In [0]:
'''Plot a gaussian curve with mean = 1.5 and standard deviation = 2.3
using numpy and matplotlib (hint: the functions you need for this is
already available in numpy, so it’s more of a googling problem)'''

import numpy as np 
import matplotlib.pyplot as plt

plt.show()

In [0]:
''' Generate a random integer vector of size 100 in which all the values are
between 0 to 10. Find the most frequent element in this vector'''
c = np.random.randint(0, 10, 100)
print(c)
print("Most frequent value in the above array:")
print(np.bincount(c).argmax())

In [0]:
'''Generate two random integer vectors of size 10 in which all the values
are from 0 to 20 and find all the common elements in both of them
'''
c= np.random.randint(0, 100, 20)
print(c)
np.random.shuffle(c)
n = 5
print (c[np.argsort(c)[-5]])

[ 3  1 79 39 74 92 94 93  7 32  4 54  7 66 67 30 61 54  9 52]
74


In [0]:
'''
Generate two random integer vectors of size 10 in which all the values
are from 0 to 20 and find all the common elements in both of them
'''
a=np.random.randint(0,20,10)
print(a)
b=np.random.randint(0,20,10)
print(b)
print(np.intersect1d(a, b))

[ 9 15  2  0  0 11 19 12 12  8]
[ 6 10 13  3  3  9  3  3  5  6]
[9]


In [0]:
'''
Generate a random integer vector of size 20 in which all the values are
from 0 to 20 and print the count of unique values in it
'''
a=np.random.randint(0,20,20)
print(a)
b=np.array(np.unique(a))
print(b.size)

[11  9 10  0  1 18 13  4 13 16  1 17  4  0  4 16 14  9  4 11]
11


In [0]:
'''
Generate a random integer vector of size 20 in which all the values are
from 0 to 20. Later, print all the elements that are smaller than 5 and
greater than 15 in the same order as they appear in the vector
'''
a=np.random.randint(0,20,20)
print("Original array: ")
print(a)
print("Values bigger than 15 =", a[a>15])
print("Values smaller than 5 =", a[a<5])


Original array: 
[ 0  9 15 12  0  9 10  3  7 18  0 14  0 14  4 12  1  7 11  6]
Values bigger than 15 = [18]
Values smaller than 5 = [0 0 3 0 0 4 1]


In [0]:
#supermarket in bitland


In [2]:
import numpy as np
robots= np.random.randint(5, size=(15, 4))
print(robots)
supermarket= np.random.randint(5, size=(7, 4))
print(supermarket)

[[1 0 3 0]
 [4 1 2 1]
 [2 0 1 4]
 [2 2 2 2]
 [4 2 2 3]
 [3 4 3 0]
 [3 4 4 0]
 [3 1 1 3]
 [2 0 0 2]
 [3 4 3 3]
 [2 1 3 3]
 [4 2 1 2]
 [1 2 3 2]
 [0 4 2 2]
 [3 4 3 0]]
[[4 2 0 2]
 [2 0 0 4]
 [4 3 2 2]
 [0 2 3 1]
 [4 3 4 1]
 [0 0 0 2]
 [4 0 1 4]]


In [3]:
#  Which robot is living in the farthest X direction?
print(robots[:,0].argmax())

#farthest Y direction
print(robots[:,1].argmax())


1
5


In [4]:
#  Which robot is living farthest from the origin?

from scipy.spatial.distance import cdist
print(cdist(robots,[[0,0,0,0]]).argmax())

9


In [5]:
# Which supermarket is in the farthest X direction
print(supermarket[:,0].argmax())

0


In [6]:
# Which supermarket is in the farthest Y direction
print(supermarket[:,1].argmax())

2


In [7]:
# Which supermarket is the farthest from the origin
print(cdist(supermarket,[[0,0,0,0]]).argmax())

4


In [8]:
#What is the distance of supermarket which is farthest from the origin
print(cdist(supermarket,[[0,0,0,0]]).max())

6.48074069840786


In [9]:
distance=cdist(robots,supermarket)
print(distance)

[[5.09901951 5.09901951 4.79583152 2.44948974 4.47213595 3.74165739
  5.38516481]
 [2.44948974 4.24264069 2.23606798 4.24264069 2.82842712 4.69041576
  3.31662479]
 [3.60555128 1.         4.24264069 4.58257569 5.56776436 3.
  2.        ]
 [2.82842712 3.46410162 2.23606798 2.44948974 3.16227766 3.46410162
  3.60555128]
 [2.23606798 3.60555128 1.41421356 4.58257569 3.         5.
  2.44948974]
 [4.24264069 6.4807407  2.64575131 3.74165739 2.         6.164414
  6.08276253]
 [5.         7.         3.16227766 3.87298335 1.73205081 6.70820393
  6.4807407 ]
 [2.         2.         2.64575131 4.24264069 4.24264069 3.46410162
  1.73205081]
 [2.82842712 2.         4.12310563 4.24264069 5.47722558 2.
  3.        ]
 [3.87298335 5.19615242 2.         4.12310563 2.64575131 5.91607978
  4.69041576]
 [3.87298335 3.31662479 3.16227766 3.         3.60555128 3.87298335
  3.16227766]
 [1.         3.60555128 1.41421356 4.58257569 3.31662479 4.58257569
  2.82842712]
 [4.24264069 4.24264069 3.31662479 1.41421

In [11]:
# What is the distance between robot 0 and supermarket 0
distance[0,0]

5.0990195135927845

In [13]:
# What is the distance between robot 2 from all the supermarkets
distance[2]

array([3.60555128, 1.        , 4.24264069, 4.58257569, 5.56776436,
       3.        , 2.        ])

In [14]:
# What is the distance of each robot from all the supermarkets
distance

array([[5.09901951, 5.09901951, 4.79583152, 2.44948974, 4.47213595,
        3.74165739, 5.38516481],
       [2.44948974, 4.24264069, 2.23606798, 4.24264069, 2.82842712,
        4.69041576, 3.31662479],
       [3.60555128, 1.        , 4.24264069, 4.58257569, 5.56776436,
        3.        , 2.        ],
       [2.82842712, 3.46410162, 2.23606798, 2.44948974, 3.16227766,
        3.46410162, 3.60555128],
       [2.23606798, 3.60555128, 1.41421356, 4.58257569, 3.        ,
        5.        , 2.44948974],
       [4.24264069, 6.4807407 , 2.64575131, 3.74165739, 2.        ,
        6.164414  , 6.08276253],
       [5.        , 7.        , 3.16227766, 3.87298335, 1.73205081,
        6.70820393, 6.4807407 ],
       [2.        , 2.        , 2.64575131, 4.24264069, 4.24264069,
        3.46410162, 1.73205081],
       [2.82842712, 2.        , 4.12310563, 4.24264069, 5.47722558,
        2.        , 3.        ],
       [3.87298335, 5.19615242, 2.        , 4.12310563, 2.64575131,
        5.91607978, 4.6

In [15]:
# Which is the nearest supermarket for robot 2
distance[2].argmin()

1

In [18]:
#Which is the nearest supermarket for each robot
distance.argmin(axis=1)

array([3, 2, 1, 2, 2, 4, 4, 6, 1, 2, 3, 0, 3, 3, 4])

In [19]:
#Which is the farthest supermarket for each robot
distance.argmax(axis=1)

array([6, 5, 4, 6, 5, 1, 1, 3, 4, 5, 0, 3, 6, 6, 1])

In [0]:
#How much units is the nearest supermarket for each robot located


In [20]:
#Which customer is nearest for supermarket 1
print(distance[:,1].argmin())

2


In [21]:
#Which customer is farthest for supermarket 1
print(distance[:,1].argmax())

6


In [22]:
#Find the nearest customer for all the supermarkets
print(distance.argmin(axis=0))

[11  2  4 12  6  8  7]


In [23]:
#What is the distance of nearest customer for all the supermarkets
print(distance.min(axis=0))

[1.         1.         1.41421356 1.41421356 1.73205081 2.
 1.73205081]


In [24]:
# If robot 2 visits each supermarket, how much distance it covers in total
distance[2,:].sum()

23.998532020369137

In [25]:
#If each robot visits each supermarket, how much distance each one covers in total
distance.sum(axis=1)

array([31.04231844, 24.00630677, 23.99853202, 21.21001701, 22.28789825,
       31.35796662, 33.95625644, 20.32718511, 23.67139901, 28.44448825,
       23.99269808, 21.32996814, 25.00445442, 32.00839172, 31.35796662])

In [26]:
#Answer previous question if supermarket 2 is shut down
distance[:,[0,1,3,4,5,6]].sum(axis=1)

array([26.24648692, 21.77023879, 19.75589133, 18.97394903, 20.87368469,
       28.71221531, 30.79397878, 17.6814338 , 19.54829339, 26.44448825,
       20.83042042, 19.91575458, 21.68782963, 27.8852861 , 28.71221531])

In [27]:
# Answer previous question if supermarket 0 and 2 are shut down
distance[:,[1,3,4,5,6]].sum(axis=1)

array([21.14746741, 19.32074905, 16.15034006, 16.14552191, 18.63761671,
       24.46957462, 25.79397878, 15.6814338 , 16.71986626, 22.5715049 ,
       16.95743707, 18.91575458, 17.44518895, 22.98630661, 24.46957462])

In [28]:
#What is the average distance each robot has to cover for visiting all supermarket
distance.mean(axis=1)

array([4.43461692, 3.4294724 , 3.42836172, 3.03000243, 3.18398546,
       4.47970952, 4.85089378, 2.90388359, 3.38162843, 4.06349832,
       3.4275283 , 3.04713831, 3.57206492, 4.57262739, 4.47970952])

In [29]:
# On an average, how far is a robot located for each supermarket
distance.mean(axis=0)

array([3.49465673, 4.20168442, 2.94424537, 3.58118238, 3.48033113,
       4.46551603, 4.09877373])

In [33]:
# If robots can only cover integral distances, find total number of reachable pairs (r,s)
dis=distance.astype(int)

mask=(dis==distance)

#print(mask)
np.argwhere(mask)


array([[ 2,  1],
       [ 2,  5],
       [ 2,  6],
       [ 4,  4],
       [ 4,  5],
       [ 5,  4],
       [ 6,  0],
       [ 6,  1],
       [ 7,  0],
       [ 7,  1],
       [ 8,  1],
       [ 8,  5],
       [ 8,  6],
       [ 9,  2],
       [10,  3],
       [11,  0],
       [14,  4]])

In [34]:
#If robots can only cover integral distances, which supermarket visits most customers
print(mask.sum(axis=0).argmax())

1


In [35]:
#If robots can only cover integral distances, find total distance covered by all robots to visit each supermarket
print((mask*dis).sum(axis=1))

[ 0  0  6  0  8  2 12  4  7  2  3  1  0  0  2]


In [0]:
#If robots can only cover integral distances, how much less does each robot travel to visit all accessible supermarkets


In [36]:
#Which robot will have to walk maximum distance in order to reach supermarket 0
print(distance[:,0].argmax())

0


In [37]:
# Calculate the distance for each robot to it’s nearest supermarket
print(distance.min(axis=1))

[2.44948974 2.23606798 1.         2.23606798 1.41421356 2.
 1.73205081 1.73205081 2.         2.         3.         1.
 1.41421356 2.44948974 2.        ]


In [38]:
#Which robot will have to walk maximum distance in order to reach it’s nearest supermarket
print(distance.min(axis=1).argmax())

10


In [39]:
#What is the distance of nearest customer for each supermarket
print(distance.min(axis=0))

[1.         1.         1.41421356 1.41421356 1.73205081 2.
 1.73205081]


In [41]:
# If all robots travel to each of the supermarket, which robot will travel the least
print(distance.sum(axis=1).argmin())

7


In [42]:
# If all robots travel to each of the supermarket, which robot will travel the most
print(distance.sum(axis=1).argmax())

6


In [43]:
#Also report the order of robots according to the total distance travelled by them in previous question (in increasing order)
distance.sum(axis=1).argsort()

array([ 7,  3, 11,  4,  8, 10,  2,  1, 12,  9,  0,  5, 14, 13,  6])

In [44]:
#Generate all (robot, supermarket) pairs where distance between them is less than 4 units
e=distance<4
np.argwhere(e)

array([[ 0,  3],
       [ 0,  5],
       [ 1,  0],
       [ 1,  2],
       [ 1,  4],
       [ 1,  6],
       [ 2,  0],
       [ 2,  1],
       [ 2,  5],
       [ 2,  6],
       [ 3,  0],
       [ 3,  1],
       [ 3,  2],
       [ 3,  3],
       [ 3,  4],
       [ 3,  5],
       [ 3,  6],
       [ 4,  0],
       [ 4,  1],
       [ 4,  2],
       [ 4,  4],
       [ 4,  6],
       [ 5,  2],
       [ 5,  3],
       [ 5,  4],
       [ 6,  2],
       [ 6,  3],
       [ 6,  4],
       [ 7,  0],
       [ 7,  1],
       [ 7,  2],
       [ 7,  5],
       [ 7,  6],
       [ 8,  0],
       [ 8,  1],
       [ 8,  5],
       [ 8,  6],
       [ 9,  0],
       [ 9,  2],
       [ 9,  4],
       [10,  0],
       [10,  1],
       [10,  2],
       [10,  3],
       [10,  4],
       [10,  5],
       [10,  6],
       [11,  0],
       [11,  1],
       [11,  2],
       [11,  4],
       [11,  6],
       [12,  2],
       [12,  3],
       [12,  4],
       [12,  5],
       [13,  3],
       [14,  2],
       [14,  3